{% set name = "riboSeed" %}
{% set version = "0.4.10b" %}
{% set hash_type = "sha256" %}
# {% set hash_value = "1dc981de89b768ca72ce77bba8b4603d" %}
#testpypi
{% set hash_value = "e3bf718e455b9b220b7caa1b5712ce440e29c179fab7139ea417c82b684809a8" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://test-files.pythonhosted.org/packages/c2/13/e8eda05bc5ad2c4ff673c7b417f8f47a52aa40858d379d141d4e9527077b/riboSeed-0.4.10b0.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: True  # [win]
  skip: True  # [py2k]
  skip: True  # [py34]
  script: python ~/GitHub/riboSeed/setup.py install
requirements:
  build:
    - python
    - setuptools
    - biopython ==1.68
    - pysam >=0.9.1.4
    - jenkspy >=0.1.3
    - pyutilsnrw >=0.0.768
    - matplotlib ==1.5.3
    - pandas ==0.20.0
    - coverage ==4.4.1
    - numpy >=1.11.2
    - nose ==1.3.7
  run:
    # python reqs
    - python
    - biopython ==1.68
    - jenkspy >=0.1.3
    - pysam >=0.9.1.4
    - pyutilsnrw >=0.0.768
    - matplotlib ==1.5.3
    - pandas ==0.20.0
    - coverage ==4.4.1
    - numpy >=1.11.2
    - nose ==1.3.7
    # sys reqs
    - emboss
    - barrnap ==0.7
    - mafft
    - prank
    - spades ==3.9.0
    - bwa ==0.7.8
    - samtools ==1.3.1

test:
  requires:
    - nose
  imports:
    - riboSeed
    - riboSeed.integration_data


about:
  home: https://github.com/nickp60/riboSeed
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: 'riboSeed: assemble across rDNA regions'
  description: "its a blast, you gotta try it!  check out the GitHub\n    repo for the read README.md file"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers:
    - nickp60
