{% set name = "minimap2" %}
{% set version = "2.1.r311" %}
{% set hash = "5e52c5f0eee156cd006f7aedaa008753" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lh3/minimap2/archive/v2.1.tar.gz 
  fn: {{ name|lower }}_{{ version }}.tar.gz
  sha256: {{ hash }}

build:
    number: 0

requirements:
    build:
        - gcc
        - zlib

    run:
        - libgcc
        - zlib
test:
  commands:
    - minimap2 2>&1 | grep 'Usage'

about:
  home: https://github.com/lh3/minimap2
  license: MIT
  summary: 'A fast sequence mapping and alignment program'
